version: '3.9'
services:
  backend:
    build: backend
    ports:
      - 8889:1323
    volumes:
      - ./backend:/app

  frontend:
    build: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 8888:8080